spring:
  application:
    name: tvmaze-middleware-api

  mongodb:
    uri: ${MONGODB_URI}

server:
  port: ${SERVER_PORT:8080}

tvmaze:
  base-url: ${TVMAZE_BASE_URL:https://api.tvmaze.com}

cache:
  ttl-hours: ${CACHE_TTL_HOURS:24}
